# Generated by Django 5.2.1 on 2025-05-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('numero_telephone', models.CharField(max_length=15)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
