# Generated by Django 5.2.1 on 2025-05-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('motif', models.CharField(max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('diagnostic', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date'],
            },
        ),
    ]
