# Generated by Django 5.2.1 on 2025-05-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('duree', models.IntegerField(help_text='Durée en jours ou en unité choisie')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Détail de prescription',
                'verbose_name_plural': 'Détails de prescription',
            },
        ),
    ]
