# Generated by Django 5.2.1 on 2025-05-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_initial'),
        ('rendez_vous', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='utilisateurs.assistant'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='utilisateurs.medecin'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='rendezvous',
            unique_together={('medecin', 'date_heure'), ('patient', 'date_heure')},
        ),
    ]
