# Generated by Django 5.2.1 on 2025-05-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('dossiers_medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='dossier_medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dossiers_medical.dossiermedical'),
        ),
    ]
